---
sidebar: sidebar 
permalink: scpivs44_concepts_overview.html 
keywords:  
summary: 适用于 VMware vSphere 的 SnapCenter 插件是一种独立虚拟设备（开放式虚拟设备格式），可为 VM 和数据存储库提供数据保护服务，并支持为基于 SnapCenter 应用程序的插件提供数据保护服务。本文档介绍如何部署和使用适用于 VMware vSphere 的 SnapCenter 插件，并提供了快速入门信息。 
---
= 产品概述
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:firstname: [.lead]
:author: [.lead]
:authorinitials: [
:authors: [.lead]
:revnumber: 
:revdate: and supports data protection services for SnapCenter application-based plug-ins. This document describes how to deploy and use SnapCenter Plug-in for VMware vSphere and includes quick start information.


适用于 VMware vSphere 的 SnapCenter 插件部署为基于 Linux 的虚拟设备。

适用于VMware vSphere的SnapCenter插件为您的环境添加了以下功能：

* 支持 VM 一致和崩溃一致的数据保护操作。
+
您可以使用 vCenter 中的 VMware vSphere 客户端用户界面执行 VMware 虚拟机（传统 VM 和 vVol VM）、VMDK 和数据存储区的所有备份和还原操作。对于 vVol VM（vVol 数据存储中的 VM），仅支持崩溃一致性备份。您还可以还原虚拟机和 VMDK，以及还原驻留在来宾操作系统上的文件和文件夹。

+
备份 VM ， VMDK 和数据存储库时，此插件不支持 RDM 。VM 的备份作业会忽略 RDM 。如果需要备份 RDM ，则必须使用基于 SnapCenter 应用程序的插件。

+
适用于VMware vSphere的SnapCenter插件包括一个MySQL数据库、其中包含适用于VMware vSphere的SnapCenter插件元数据。为了实现虚拟机一致和崩溃状态一致的数据保护，您无需安装 SnapCenter 服务器。

* 支持应用程序一致的（基于 VMDB/RDM 的应用程序）数据保护操作。
+
您可以使用SnapCenter用户界面和适当的SnapCenter应用程序插件对虚拟机上主存储和二级存储上的数据库和文件系统执行所有备份和恢复操作。

+
SnapCenter本机利用适用于VMware vSphere的SnapCenter插件对VMDK、原始设备映射(Raw Device Mappings、RDM)和NFS数据存储库执行所有数据保护操作。部署虚拟设备后，此插件将处理与 vCenter 的所有交互。适用于VMware vSphere的SnapCenter插件支持所有基于SnapCenter应用程序的插件。

+
SnapCenter不支持数据库和虚拟机的单个快照。必须独立安排和运行虚拟机和数据库的备份，这会创建单独的快照，即使数据库和虚拟机托管在同一卷中。使用SnapCenter用户界面安排数据库应用程序备份；使用 VMware vSphere 客户端用户界面安排 VM 和数据存储区备份。

* 要创建VM一致的快照、需要使用VMware工具
+
如果未安装并运行VMware工具、则不会使文件系统处于静置状态、而是会创建崩溃状态一致的快照。

* 在 SAN （ VMFS ）环境中执行还原操作需要使用 VMware Storage vMotion
+
VMware 文件系统（ VMFS ）的还原工作流利用了 VMware Storage vMotion 功能。Storage vMotion 是 vSphere 标准许可证的一部分，但 vSphere Essentials 或 Essentials Plus 许可证不提供。

+
NFS 环境中的大多数还原操作都使用原生 ONTAP 功能（例如单个文件 SnapRestore ），而不需要 VMware Storage vMotion 。

* 要配置VMware vVol VM、需要使用适用于VMware vSphere的ONTAP工具。
+
您可以使用ONTAP 工具在ONTAP 和VMware Web Client中为VVOL配置和配置存储。

+
有关更多信息，请参阅适用ONTAP tools for VMware vSphere文档。此外，请参阅 https://imt.netapp.com/imt/imt.jsp?components=180121;&solution=1517&isHWU&src=IMT["NetApp 互操作性表工具"^]有关ONTAP工具支持的版本的最新信息。

* 适用于VMware vSphere的SnapCenter插件作为虚拟设备部署在Linux VM中
+
尽管虚拟设备必须作为Linux VM安装、但适用于VMware vSphere的SnapCenter插件同时支持基于Windows和基于Linux的vCenter。SnapCenter 本机使用此插件，无需用户干预，即可与 vCenter 进行通信，以支持基于 SnapCenter 应用程序的插件，这些插件可在 Windows 和 Linux 虚拟化应用程序上执行数据保护操作。



除了这些主要功能之外、适用于VMware vSphere的SnapCenter插件还支持iSCSI、光纤通道、FCoE、NFS 3.0/4.1、VMFS 5.0/6.0、基于FC的NVMe以及基于TCP的NVMe。

有关受支持版本的最新信息，请参阅 https://imt.netapp.com/imt/imt.jsp?components=180121;&solution=1517&isHWU&src=IMT["NetApp 互操作性表工具"^]（IMT）。

有关NFS协议和ESXi主机的信息、请参阅VMware提供的vSphere存储文档。

有关SnapCenter数据保护的信息，请参阅中SnapCenter插件的数据保护信息 http://docs.netapp.com/us-en/snapcenter/index.html["SnapCenter 文档"^]。

有关支持的升级和迁移路径的信息，请参见 link:scpivs44_release_notes.html["适用于 VMware vSphere 的 SnapCenter 插件发行说明"^]。
