---
sidebar: sidebar 
permalink: scpivs44_manage_policies.html 
keywords:  
summary: 您可以为适用于 VMware vSphere 的 SnapCenter 插件创建，修改，查看，断开和删除备份策略。执行数据保护操作需要策略。 
---
= 管理策略
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以为适用于 VMware vSphere 的 SnapCenter 插件创建，修改，查看，断开和删除备份策略。执行数据保护操作需要策略。



== 分离策略

如果您不再希望适用于VMware vSphere的SnapCenter插件资源组中的策略用于管理资源的数据保护、则可以将这些策略与这些策略断开。必须先断开策略，然后才能将其删除或修改计划频率。

.关于此任务
从适用于VMware vSphere的SnapCenter插件资源组中分离策略的准则与SnapCenter资源组的准则不同。对于VMware vSphere客户端资源组、可以断开所有策略、这样就会使资源组无策略。但是，要对该资源组执行任何数据保护操作，必须至少附加一个策略。

.步骤
. 在选择控制阀插件的左侧导航窗格中，单击*Resource Groups*，然后选择一个资源组并单击*Edit*。
. 在 * 编辑资源组 * 向导的 * 策略 * 页面上，清除要断开的策略旁边的复选标记。
+
您也可以通过检查策略向资源组添加策略。

. 在向导的其余部分中对资源组进行任何其他修改，然后单击 * 完成 * 。




== 修改策略

您可以修改适用于 VMware vSphere 的 SnapCenter 插件资源组的策略。  在将策略附加到资源组时、您可以修改频率、复制选项、Snapshot保留设置或脚本信息。

.关于此任务
修改适用于VMware vSphere的SnapCenter插件备份策略与修改基于SnapCenter应用程序的插件的备份策略不同。修改插件策略时，您无需将策略与资源组分离。

在修改复制或保留设置之前，应考虑可能的后果。

* 增加复制或保留设置
+
备份会持续累积，直到达到新设置为止。

* 降低复制或保留设置
+
执行下一次备份时，系统将删除超出新设置的备份。




NOTE: 要修改适用于VMware vSphere的SnapCenter插件策略计划、必须在插件资源组中修改该计划。

.步骤
. 在选择控制阀插件的左侧导航窗格中，单击*Policies*，然后选择一个策略并单击*Edit*。
. 修改策略字段。
. 完成后，单击 * 更新 * 。


这些更改将在执行下一次计划备份时生效。



== 删除策略

如果您不再需要为适用于 VMware vSphere 的 SnapCenter 插件配置备份策略，则可能需要将其删除。

.开始之前
您必须先将策略与 SnapCenter 虚拟设备中的所有资源组断开连接，然后才能将其删除。

.步骤
. 在选择控制阀插件的左侧导航窗格中，单击*Policies*，然后选择一个策略并单击*Remove*。
. 在确认对话框中，单击 * 确定 * 。

