---
sidebar: sidebar 
permalink: scpivs44_manage_resource_groups.html 
keywords:  
summary: 您可以创建，修改和删除备份资源组，并对资源组执行备份操作。 
---
= 管理资源组
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以创建，修改和删除备份资源组，并对资源组执行备份操作。


NOTE: 资源组在 Virtual Storage Console （ VSC ）中称为备份作业。



== 暂停和恢复对资源组的操作

您可以暂时禁止对资源组启动计划的操作。稍后，您可以根据需要启用这些操作。

.步骤
. 在选择控制阀插件的左侧导航窗格中，单击*Resource Groups*，选择一个资源组，然后单击*挂起*(或单击*Resume*)。
. 在确认框中，单击 * 确定 * 进行确认。


.完成后
在资源组页面上，已暂停资源的作业状态为 `unle_Maintenance` 。您可能需要滚动到表的右侧才能查看作业状态列。

恢复备份操作后，作业状态将更改为 `生产` 。



== 修改资源组

您可以在 vCenter 中的资源组中删除或添加资源，断开或附加策略，修改计划或修改任何其他资源组选项。

.关于此任务
如果要修改资源组的名称，请勿在 VM ，数据存储库，策略，备份或资源组名称中使用以下特殊字符：

% 和 * $ # @ ！\ / ： * ？" < >-| ； " ，。

允许使用下划线字符（ _ ）。

.步骤
. 在选择控制阀插件的左侧导航窗格中，单击*Resource Groups*，然后选择一个资源组并单击*Edit*。
. 在 * 编辑资源组 * 向导的左侧列表中，单击要修改的类别并输入所做的更改。
+
您可以在多个类别中进行更改。

. 单击 * 下一步 * ，直到显示摘要页面，然后单击 * 完成 * 。




== 删除资源组

如果您不再需要保护 vCenter 中的资源，则可以删除该资源组。在从 vCenter 中删除适用于 VMware vSphere 的 SnapCenter 插件之前，必须确保删除所有资源组。

.关于此任务
所有资源组删除操作均以强制删除的形式执行。此删除操作会从vCenter资源组中断开所有策略、从适用于VMware vSphere的SnapCenter插件中删除此资源组、并删除此资源组的所有备份和快照。


NOTE: 在SnapVault关系中、无法删除最后一个Snapshot；因此、无法删除资源组。删除SnapVault关系中的资源组之前、必须使用OnCommand系统管理器或ONTAP命令行界面删除SnapVault关系、然后删除最后一个Snapshot。

.步骤
. 在选择控制阀插件的左侧导航窗格中，单击*Resource Groups*，然后选择一个资源组并单击*Delete*。
. 在 * 删除资源组 * 确认框中，单击 * 确定 * 进行确认。

