---
sidebar: sidebar 
permalink: scpivs44_mount_a_backup.html 
keywords:  
summary: 如果要访问备份中的文件，可以从备份挂载传统数据存储库。您可以将备份挂载到创建备份的同一 ESXi 主机，也可以挂载到具有相同类型的 VM 和主机配置的备用 ESXi 主机。您可以在主机上多次挂载数据存储库。 
---
= 挂载备份
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
如果要访问备份中的文件，可以从备份挂载传统数据存储库。您可以将备份挂载到创建备份的同一 ESXi 主机，也可以挂载到具有相同类型的 VM 和主机配置的备用 ESXi 主机。您可以在主机上多次挂载数据存储库。

您无法挂载 VVol 数据存储库。

.开始之前
* 确保备用 ESXi 主机可以连接到存储
+
如果要挂载到备用 ESXi 主机，则必须确保备用 ESXi 主机可以连接到存储，并且具有以下功能： * 与原始主机的 UID 和 GID 相同 * 适用于 VMware vSphere 的 SnapCenter 插件的虚拟设备与原始主机的虚拟设备版本相同

* 将存储启动程序映射到 ESXi
+
确保存储系统的启动程序已映射到 ESXi 。

* 清理陈旧的 LUN
+
由于 ESXi 只能在每个数据存储库中发现一个唯一的 LUN ，因此如果发现多个 LUN ，则操作将失败。如果在上次挂载操作完成之前启动挂载操作，或者手动克隆 LUN ，或者在卸载操作期间未从存储中删除克隆，则可能会发生这种情况。为了避免发现多个克隆，您应清理存储上所有陈旧的 LUN 。



如果数据存储库所在的 FabricPool 存储层不可用，则挂载操作可能会失败。

.步骤
. 在 VMware vSphere Web Client 中，单击工具栏中的 * 菜单 * ，然后从下拉列表中选择 * 存储 * 。
. 右键单击某个数据存储库并在 SnapCenter 下拉列表中选择 * NetApp Backup* ，然后在二级下拉列表中选择 * 挂载备份 * 。
. 在 * 挂载数据存储库 * 页面上，选择备份和备份位置（主或二级），然后单击 * 完成 * 。
. 可选：要验证是否已挂载数据存储库，请执行以下操作：
+
.. 单击工具栏中的 * 菜单 * ，然后从下拉列表中选择 * 存储 * 。
.. 左侧导航器窗格将在列表顶部显示您挂载的数据存储库。
+
如果在受 SnapVault 计划保护且运行 ONTAP 8.3 的 SnapVault 目标卷上执行连接或挂载操作，则可能会在连接或挂载对话框屏幕中显示一个额外的 Snapshot 副本。发生这种情况的原因是，连接或挂载操作会克隆 SnapVault 目标卷，而 ONTAP 会通过创建新的 Snapshot 副本来更新此卷。

+
要防止在克隆卷时创建新的 Snapshot 副本，请关闭 SnapVault 卷的 ONTAP 计划。不会删除以前存在的 Snapshot 副本。




