---
sidebar: sidebar 
permalink: scpivs44_deploy_snapcenter_plug-in_for_vmware_vsphere.html 
keywords:  
summary: 要使用 SnapCenter 功能保护虚拟机上的 VM ，数据存储库和应用程序一致的数据库，您必须部署适用于 VMware vSphere 的 SnapCenter 插件。 
---
= 部署适用于 VMware vSphere 的 SnapCenter 插件
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
要使用 SnapCenter 功能保护虚拟机上的 VM ，数据存储库和应用程序一致的数据库，您必须部署适用于 VMware vSphere 的 SnapCenter 插件。

.开始之前
本节列出了在开始部署之前应执行的所有必要操作。


NOTE:  VMware vCenter 7u1及更高版本支持OVA部署。

* 确保您已查看部署要求。
* 验证您正在运行受支持的 vCenter Server 版本。
* 确认您的 vCenter Server 环境已配置并设置。
* SnapCenter Plug-in for VMware vSphere准备 ESXi 主机。
* 下载SnapCenter Plug-in for VMware vSphere。
* 获取 vCenter Server 实例的登录凭据。
* 获取具有有效公钥和私钥文件的证书。有关详细信息，请参阅 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/SnapCenter_Certificate_Resolution_Guide["存储证书管理"]部分。
* 注销并关闭所有 vSphere 客户端浏览器会话，并清除浏览器缓存以防止部署期间出现问题。
* 在 vCenter 中启用传输层安全性 (TLS)。请参阅 VMware 文档。
* 如果您计划在部署了适用于SnapCenter Plug-in for VMware vSphere的vCenter 以外的 vCenter 中执行备份，请确保 ESXi 服务器、SnapCenter Plug-in for VMware vSphere和每个 vCenter 都同步到同一时间。
* 要保护 vVol 数据存储上的虚拟机，请首先ONTAP tools for VMware vSphere。有关受支持的ONTAP工具版本，请参阅 https://imt.netapp.com/imt/imt.jsp?components=180121;&solution=1517&isHWU&src=IMT["NetApp 互操作性表工具"^]。ONTAP工具在ONTAP和 VMware Web 客户端上配置和配置存储。


在与vCenter相同的时区部署适用于VMware vSphere的SnapCenter插件。备份计划在部署适用于VMware vSphere的SnapCenter插件的时区执行。 vCenter按vCenter所在时区报告数据。因此、如果适用于VMware vSphere的SnapCenter插件和vCenter位于不同的时区、则适用于VMware vSphere的SnapCenter插件信息板中的数据可能与报告中的数据不同。

.步骤
. 对于VMware vCenter 7.0.3及更高版本、请按照中的步骤进行操作 link:scpivs44_download_the_ova_open_virtual_appliance.html["下载Open Virtual Appliance (OVA)"^] 将证书导入到vCenter。
. 在浏览器中，导航到 VMware vSphere vCenter 。
+

NOTE: 对于IPv6地址HTML Web客户端、必须使用Chrome或Firefox。

. 登录到 * VMware vCenter Single Sign-On* 页面。
. 在导航器窗格中，右键单击任何作为虚拟机的有效父对象(例如数据中心、集群或主机)的清单对象，然后选择*Deploy OVF Template *(部署OVF模板)以启动VMware Deploy向导。
. 解压缩包含.ova文件的.tar文件到本地系统。在*选择OVF模板*页面上、指定的位置 `.ova` 已提取.tar文件夹中的文件。
. 选择 * 下一步 * 。
. 在*选择名称和文件夹*页面上，输入VM或vApp的唯一名称，并选择部署位置，然后选择*下一步*。
+
此步骤指定导入位置 `.tar` 文件到vCenter中。虚拟机的默认名称与选定的名称相同 `.ova` 文件如果更改了默认名称，请在每个 vCenter Server VM 文件夹中选择一个唯一的名称。

+
VM 的默认部署位置是启动向导的清单对象。

. 在“*选择资源*”页面上，选择要运行已部署VM模板的资源，然后选择“*下一步*”。
. 在*查看详细信息*页面上，验证 `.tar`模板详细信息并选择*下一步*。
. 在 * 许可协议 * 页面上，选中 * 我接受所有许可协议 * 复选框。
. 在 * 选择存储 * 页面上，定义为已部署的 OVF 模板存储文件的位置和方式。
+
.. 选择 VMDK 的磁盘格式。
.. 选择 VM 存储策略。
+
只有在目标资源上启用了存储策略时，此选项才可用。

.. 选择一个数据存储库以存储已部署的 OVA 模板。
+
配置文件和虚拟磁盘文件存储在数据存储库中。

+
选择一个足以容纳虚拟机或 vApp 以及所有关联虚拟磁盘文件的数据存储库。



. 在 * 选择网络 * 页面上，执行以下操作：
+
.. 选择一个源网络并将其映射到一个目标网络，
+
源网络列列出了 OVA 模板中定义的所有网络。

.. 在*IP分配设置*部分，选择所需的IP地址协议，然后选择*Next*。
+
适用于 VMware vSphere 的 SnapCenter 插件支持一个网络接口。如果需要多个网络适配器，则必须手动设置。请参阅 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_create_additional_network_adapters_in_NDB_and_SCV_4.3["知识库文章：如何创建其他网络适配器"^]。



. 在 * 自定义模板 * 页面上，执行以下操作：
+
.. 在 * 注册到现有 vCenter * 部分中，输入虚拟设备的 vCenter 名称和 vCenter 凭据。
+
在 * vCenter username* 字段中，输入格式为 `domain\username` 的用户名。

.. 在 * 创建 SCV 凭据 * 部分中，输入本地凭据。
+
在 * 用户名 * 字段中，输入本地用户名；不包括域详细信息。

+

IMPORTANT: 记下您指定的用户名和密码。如果要稍后修改适用于VMware vSphere的SnapCenter插件配置、则需要使用这些凭据。

.. 输入maint用户的凭据。
.. 在*设置网络属性*部分，输入主机名。
+
... 在*Setup IPv4 Network Properties"(设置IPv4网络属性)部分，输入网络信息，例如IPv4地址、IPv4网络掩码、IPv4网关、IPv4 Primary DNS、IPv4 Secondary DNS、 和IPv4搜索域。
... 在*设置IPv6网络属性*部分，输入网络信息，如IPv6地址、IPv6网络掩码、IPv6网关、IPv6主DNS、IPv6二级DNS、 和IPv6搜索域。
+
选择IPv4或IPv6地址字段、或者选择这两者(如果适用)。如果同时使用IPv4和IPv6地址、则只需要为其中一个地址指定主DNS。

+

IMPORTANT: 如果要继续使用 DHCP 作为网络配置，可以跳过这些步骤并将 * 设置网络属性 * 部分中的条目留空。



.. 在 * 设置日期和时间 * 中，选择 vCenter 所在的时区。


. 在*Ready to Complete*(准备完成)页面上，查看该页面并选择*Complete*(完成)。
+
所有主机都必须配置 IP 地址（不支持 FQDN 主机名）。在部署之前， Deploy 操作不会验证您的输入。

+
在等待 OVF 导入和部署任务完成时，您可以从 " 近期任务 " 窗口查看部署进度。

+
成功部署适用于VMware vSphere的SnapCenter插件后、该插件将部署为Linux VM、并注册到vCenter中、同时安装VMware vSphere客户端。

. 导航到部署了适用于VMware vSphere的SnapCenter插件的虚拟机，选择*Summary (摘要)*选项卡，然后选择*Power On*(开机)框以启动虚拟设备。
. 在适用于VMware vSphere的SnapCenter插件启动时，右键单击已部署的适用于VMware vSphere的SnapCenter插件，选择*Guest OS*，然后选择*Install VMware tools*。
+
VMware工具安装在部署适用于VMware vSphere的SnapCenter插件的虚拟机上。有关安装VMware工具的详细信息、请参见VMware文档。

+
完成部署可能需要几分钟时间。如果适用于VMware vSphere的SnapCenter插件已启动、VMware工具已安装、并且屏幕提示您登录到适用于VMware vSphere的SnapCenter插件、则表示部署成功。您可以在首次重新启动期间将网络配置从 DHCP 切换到静态。但是，不支持从静态切换到 DHCP 。

+
屏幕显示部署SnapCenter Plug-in for VMware vSphere的IP 地址。记下 IP 地址。如果要更改适用于SnapCenter Plug-in for VMware vSphere配置，则需要登录到适用SnapCenter Plug-in for VMware vSphere管理用户界面。

. 使用部署屏幕上显示的 IP 地址和部署向导中提供的凭据登录到适用SnapCenter Plug-in for VMware vSphere管理用户界面，然后在仪表板上验证适用SnapCenter Plug-in for VMware vSphere是否已成功连接到 vCenter 并已启用。
+
使用格式 `\https://<appliance-IP-address>:8080`访问管理用户界面。

+
使用部署时设置的管理员用户名和密码以及使用维护控制台生成的MFA令牌登录。

+
如果未启用适用于VMware vSphere的SnapCenter插件，请参阅 link:scpivs44_restart_the_vmware_vsphere_web_client_service.html["重新启动VMware vSphere客户端服务"]。

+
如果主机名称为 "UnifiedVSC/SCV ，则重新启动设备。如果重新启动设备时未将主机名更改为指定的主机名，则必须重新安装该设备。



.完成后
您应完成所需的 link:scpivs44_post_deployment_required_operations_and_issues.html["部署后操作"]。
