---
sidebar: sidebar 
permalink: scpivs44_manage_resource_groups.html 
keywords:  
summary: 您可以创建，修改和删除备份资源组，并对资源组执行备份操作。 
---
= 管理资源组
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以创建，修改和删除备份资源组，并对资源组执行备份操作。


NOTE: 资源组在 Virtual Storage Console （ VSC ）中称为备份作业。



== 暂停和恢复对资源组的操作

暂停资源组上的计划操作。需要时再次启用它们。

.步骤
. 在选择控制阀插件的左侧导航窗格中，选择*资源组*，选择资源组，然后选择*暂停*(或选择*恢复*)。
. 在确认框中，选择*OK*进行确认。


.完成后
在资源组页面上，已暂停资源的作业状态为 `unle_Maintenance` 。您可能需要滚动到表的右侧才能查看作业状态列。

恢复备份操作后，作业状态将更改为 `生产` 。



== 修改资源组

您可以在 vCenter 中的资源组中删除或添加资源，断开或附加策略，修改计划或修改任何其他资源组选项。

.关于此任务
如果要修改资源组的名称，请勿在 VM ，数据存储库，策略，备份或资源组名称中使用以下特殊字符：

% 和 * $ # @ ！\ / ： * ？“ < > - | ; ' ，以及空格。允许使用下划线字符（ _ ）。

.步骤
. 在选择控制阀插件的左侧导航窗格中，选择*资源组*，然后选择资源组并选择*编辑*。
. 在*Edit Resource Group*向导的左侧列表中，选择要修改的类别并输入所做的更改。
+
您可以在多个类别中进行更改。您还可以在此选项中编辑受二级保护的资源。

. 选择*Next*直到出现“摘要”页面，然后选择*Complet*。




== 删除资源组

如果不需要保护资源，请删除 vCenter 中的资源组。删除适用SnapCenter Plug-in for VMware vSphere之前，请删除所有资源组。

.关于此任务
所有资源组删除操作均以强制删除的方式执行。删除资源组时，系统会从 vCenter 资源组分离所有策略，从SnapCenter Plug-in for VMware vSphere中删除该资源组，并删除该资源组的所有备份和快照。


NOTE: 在SnapVault关系中，您无法删除最后一个快照，因此您无法删除资源组。在删除SnapVault关系中的资源组之前，请使用 System Manager 或ONTAP CLI 删除该关系，然后删除最后一个快照。

.步骤
. 在选择控制阀插件的左侧导航窗格中，选择*资源组*，然后选择资源组并选择*删除*。
. 在*删除资源组*确认对话框中，选择*确定*进行确认。删除资源组并不会删除二级保护。如果需要，使用系统管理器删除二级保护。为资源组创建的一致性组不会自动删除；您必须使用系统管理器或其他受支持的界面从ONTAP中手动删除它们。

