---
sidebar: sidebar 
permalink: scpivs44_post-migration.html 
keywords:  
summary: 将备份元数据迁移到适用于 VMware vSphere 的 SnapCenter 插件后可能会遇到的问题。 
---
= 迁移后
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
将备份元数据迁移到适用于 VMware vSphere 的 SnapCenter 插件后可能会遇到的问题。

* 迁移日志包
+
从 SnapCenter 安装文件夹中的 `App_Data/MigrationLog` 目录下载迁移日志包。保留迁移日志包，直到确定迁移成功为止。

* 信息板上的作业详细信息
+
迁移后的备份信息会列在 VMware vSphere Web Client 的近期作业窗格中，但详细信息不会显示在信息板中，直到迁移后执行备份为止。

* 身份验证错误
+
如果不使用管理员凭据，则可能会遇到身份验证错误。

+
link:scpivs44_manage_authentication_errors.html["管理身份验证错误"]

* 备份名称
+
迁移前备份名称的格式为： ` 名称` 主机名 _Timestamp 。例如， ` -nas_ds_rg_perf1server_07-05-2019_02.11.59.9338` 。

+
迁移后备份名称的格式为 `RGName_Timestamp` 。

+
例如， ` -nas_vm_rg_07-2019_21.20.00.0609` 。

* 预脚本和后脚本
+
为资源组配置的脚本不会迁移。由于为 Windows 系统编写的脚本可能无法在基于 Linux 的虚拟设备上运行，因此您可能需要重新创建全部或部分脚本，并在迁移后添加这些脚本。例如， Linux 中不存在 Windows 中的文件路径，在 Linux 中无法调用 ` .bat` 批处理文件。

+
其中一个解决方案是将现有的基于 Windows 的脚本放在基于 Linux 的虚拟设备上，并测试该脚本是否可以正常运行而不进行任何更改。如果此命令无法正常运行，请将脚本中基于 Windows 的每个命令替换为相应的 Linux 兼容命令。

* 子文件还原凭据
+
不会迁移子系统文件还原凭据。因此，您必须在迁移后创建新的子文件凭据。

* `sCBR.override` 配置文件
+
如果您已在 `sCBR.override` 配置文件中自定义设置，则必须将该文件移动到 SnapCenter VMware 插件虚拟设备并重新启动 Web 客户端服务。

* 升级基于 SnapCenter 应用程序的插件
+
如果您使用 SnapCenter VMware 插件支持其他 SnapCenter 插件，则必须将这些插件更新到 4.2 或更高版本。

* 卸载 SnapCenter 服务器
+
如果您仅使用 SnapCenter 保护 VM 一致或崩溃一致的数据，则在将所有 VM 备份迁移到 SnapCenter VMware 插件后，您可以在 Windows 主机上卸载 SnapCenter 服务器


