---
sidebar: sidebar 
permalink: scpivs44_guest_file_restore_scenarios_you_might_encounter.html 
keywords:  
summary: 尝试还原子文件时，可能会遇到以下情形：子文件还原会话为空，子文件还原连接磁盘操作失败或在子文件还原会话中断后备份未断开。 
---
= 可能会遇到的子系统文件还原情形
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
尝试还原子文件时，您可能会遇到以下任何情形。



== 子文件还原会话为空

创建子系统文件还原会话时会发生此问题描述，而在该会话处于活动状态时，子系统将重新启动。如果发生这种情况，子操作系统中的 VMDK 可能会保持脱机状态。因此，当您尝试浏览子文件还原会话时，此列表为空。

要更正问题描述，请手动将 VMDK 重新置于子操作系统中的联机状态。当 VMDK 联机时，子文件还原会话将显示正确的内容。



== 子系统文件还原连接磁盘操作失败

启动子系统文件还原操作时会发生此问题、但即使VMware工具正在运行且子操作系统凭据正确、连接磁盘操作也会失败。如果发生这种情况，将返回以下错误：

`验证子系统凭据时出错，无法使用指定凭据访问子系统：验证 VMware 工具是否在系统上正常运行，使用的帐户是否为管理员帐户，错误是系统错误 VIX 错误代码 = （ 3016 ， 0 ）。`

要更正问题描述，请在子操作系统上重新启动 VMware Tools Windows 服务，然后重试子文件还原操作。



== 访客电子邮件显示？？？？？文件名

如果您使用子文件还原功能还原名称中包含非英语字符的文件或文件夹，并且电子邮件通知显示 " ？？？？？？ " ，则会出现此问题描述 " 。电子邮件附件正确列出了已还原文件和文件夹的名称。



== 子系统文件还原会话中断后，备份不会断开

当您从 VM 一致的备份执行子系统文件还原操作时，会发生此问题描述。当子系统文件还原会话处于活动状态时，会为同一个 VM 执行另一个 VM 一致的备份。如果子系统文件还原会话断开连接（手动断开或在 24 小时后自动断开），则不会断开会话的备份。

要更正问题描述，请手动断开与活动子文件还原会话连接的 VMDK 。
