---
sidebar: sidebar 
permalink: scpivs44_mount_a_backup.html 
keywords:  
summary: 如果要访问备份中的文件，可以从备份挂载传统数据存储库。您可以将备份挂载到创建备份的同一 ESXi 主机，也可以挂载到具有相同类型的 VM 和主机配置的备用 ESXi 主机。您可以在主机上多次挂载数据存储库。 
---
= 挂载备份
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
如果要访问备份中的文件，可以从备份挂载传统数据存储库。您可以将备份挂载到创建备份的同一 ESXi 主机，也可以挂载到具有相同类型的 VM 和主机配置的备用 ESXi 主机。您可以在主机上多次挂载数据存储库。

您无法挂载 VVol 数据存储库。

.开始之前
* 确保备用 ESXi 主机可以连接到存储
+
如果要挂载到备用ESXi主机、则必须确保备用ESXi主机可以连接到存储、并且具有以下配置：

+
** 与原始主机的 UID 和 GID 相同
** 适用于VMware vSphere的SnapCenter插件虚拟设备的版本与原始主机相同


* 使用iSCSI协议时、请确保存储系统的启动程序已映射到ESXi主机。使用NVMe协议时、请添加控制器以将所需子系统映射到ESXi主机。
* 清理陈旧的LUN /命名空间
+
由于ESXi主机只能在每个数据存储库中发现一个唯一的LUN或命名空间、因此、如果找到多个LUN或命名空间、此操作将失败。如果您在上一个挂载操作完成之前启动了挂载操作、或者您手动克隆了LUN /命名空间、或者在卸载操作期间未从存储中删除克隆、则可能会出现此问题。为了避免发现多个克隆、您应清理存储上所有陈旧的LUN /命名空间。



.关于此任务
如果数据存储库所在的 FabricPool 存储层不可用，则挂载操作可能会失败。

.步骤
. 在VMware vSphere客户端快捷方式页面中、选择*存储*。
. 右键单击某个数据存储库并选择*适用于VMware vSphere的SnapCenter插件*>*挂载备份*。
. 在 * 挂载数据存储库 * 页面上，选择备份和备份位置（主或二级），然后单击 * 完成 * 。
. 可选：要验证是否已挂载数据存储库，请执行以下操作：
+
.. 单击工具栏中的 * 菜单 * ，然后从下拉列表中选择 * 存储 * 。
.. 左侧导航器窗格会在列表顶部显示您挂载的数据存储库。
+
如果您对受SnapVault计划保护且运行ONTAP 8.3的SnapVault目标卷执行连接或挂载操作、则可能会在连接或挂载对话框屏幕中显示一个额外的Snapshot。出现这种情况的原因是、连接或挂载操作会克隆SnapVault目标卷、而ONTAP会通过创建新的Snapshot来更新此卷。

+
要防止在克隆卷时创建新的快照、请关闭SnapVault卷的ONTAP计划。不会删除先前的现有快照。




