---
sidebar: sidebar 
permalink: scpivs44_remove_plugin.html 
keywords:  
summary: 如果您不再需要使用SnapCenter数据保护功能、则必须禁用适用于VMware vSphere的SnapCenter插件以将其从vCenter中注销、然后从vCenter中删除适用于VMware vSphere的SnapCenter插件、最后手动删除剩余文件。 
---
= 删除适用于 VMware vSphere 的 SnapCenter 插件
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
如果您不再需要使用SnapCenter数据保护功能、则必须禁用适用于VMware vSphere的SnapCenter插件以将其从vCenter中注销、然后从vCenter中删除适用于VMware vSphere的SnapCenter插件、最后手动删除剩余文件。

.开始之前
* 您必须具有管理员权限。
* 确保未运行任何 SnapCenter 作业。


.步骤
. 使用格式登录到适用于VMware vSphere的SnapCenter插件管理GUI `\https://<OVA-IP-address>:8080`。
+
部署适用于VMware vSphere的SnapCenter插件时、将显示此插件的IP地址。

. 在左侧导航窗格中选择*配置*，然后取消选择*插件详细信息*部分中的服务选项以禁用该插件。
. 登录到 VMware vSphere 。
. 在左侧导航屏幕中，右键单击适用于VMware vSphere的SnapCenter插件实例(部署虚拟设备时使用的文件名 `.tar` )，然后选择*Delete from Disk*(从磁盘删除)。
. 如果您已使用适用于VMware vSphere的SnapCenter插件支持其他SnapCenter插件进行应用程序一致的备份、请登录到SnapCenter并删除vSphere主机。


.完成后
此时仍会部署此虚拟设备、但会删除适用于VMware vSphere的SnapCenter插件。

在删除适用于VMware vSphere的SnapCenter插件的主机VM后、此插件可能仍会在vCenter中列出、直到刷新本地vCenter缓存为止。但是，由于已删除此插件，因此无法对该主机执行任何 SnapCenter VMware vSphere 操作。如果要刷新本地vCenter缓存、请先确保此设备在适用于VMware vSphere的SnapCenter插件配置页面上处于已禁用状态、然后重新启动vCenter Web Client服务。
