---
sidebar: sidebar 
permalink: scpivs44_restore_guest_files_and_folders_from_vmdks.html 
keywords:  
summary: 您可以从 Windows 子操作系统上的 VMDK 还原一个或多个文件或文件夹。 
---
= 从 VMDK 还原子系统文件和文件夹
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以从 Windows 子操作系统上的 VMDK 还原一个或多个文件或文件夹。

默认情况下，连接的虚拟磁盘将在 24 小时内可用，然后会自动断开连接。您可以在向导中选择在还原操作完成时自动删除会话，也可以随时手动删除子系统文件还原会话，或者可以在 * 子系统配置 * 页面中延长此时间。

子系统文件或文件夹还原性能取决于两个因素：要还原的文件或文件夹的大小；以及要还原的文件或文件夹的数量。如果要还原的数据集大小相同，则与还原少量大文件相比，还原大量小文件所需的时间可能会比预期长。


IMPORTANT: 一个 VM 只能同时运行一个连接或还原操作。不能在同一个 VM 上运行并行连接或还原操作。


IMPORTANT: 通过子系统还原功能，您可以查看和还原系统和隐藏文件以及查看加密文件。请勿尝试覆盖现有系统文件或将加密文件还原到加密文件夹。在还原操作期间，子文件的隐藏属性，系统属性和加密属性不会保留在还原的文件中。查看或浏览预留的分区可能会出现发生原因错误。

.步骤
. 单击 * 菜单 * 并选择 * 主机和集群 * 菜单选项，然后选择一个虚拟机，再选择 * NetApp SnapCenter * ，然后单击 * 来宾文件还原 * 。
. 在 VMware vSphere Web Client 中，从二级下拉列表中单击 * 子文件还原 * 以启动向导。
. 在 * 还原范围 * 页面上，通过执行以下操作指定包含要连接的虚拟磁盘的备份：
+
.. 在 * 备份名称 * 表中，选择包含要连接的虚拟磁盘的备份。
.. 在 * VMDK* 表中，选择包含要还原的文件或文件夹的虚拟磁盘。
.. 在 * 位置 * 表中，选择要连接的虚拟磁盘的主或二级位置。


. 在 * 来宾详细信息 * 页面上，执行以下操作。
+
.. 选择要将虚拟磁盘连接到的位置：
+
|===
| 选择此选项… | 如果为… 


| 使用来宾 VM  a| 
您希望将虚拟磁盘连接到在启动向导之前右键单击的虚拟机，然后为右键单击的虚拟机选择凭据。


NOTE: 必须已为此虚拟机创建凭据。



| 使用子系统文件还原代理 VM  a| 
您希望将虚拟磁盘连接到代理 VM ，然后选择代理 VM 。


NOTE: 在连接和还原操作开始之前，必须配置代理 VM 。

|===
.. 选择 * 发送电子邮件通知 * 选项。
+
如果您希望在连接操作完成时收到通知，并且虚拟磁盘可用，则需要此选项。此通知电子邮件包括虚拟磁盘名称，虚拟机名称以及为 VMDK 新分配的驱动器号。

+

TIP: 启用此选项，因为子系统文件还原是一项异步操作，并且可能存在为您建立子系统会话的时间延迟。

+
此选项将使用在 vCenter 中设置 VMware vSphere Web Client 时配置的电子邮件设置。



. 查看摘要，然后单击 * 完成 * 。
+
在单击 * 完成 * 之前，您可以返回到向导中的任何页面并更改信息。

. 请等待连接操作完成。
+
您可以在信息板作业监控器中查看操作进度，也可以等待电子邮件通知。

. 要查找要从连接的虚拟磁盘还原的文件，请单击 * 菜单 > 适用于 VMware vSphere 的 SnapCenter 插件 * ，然后在左侧导航器窗格中单击 * 来宾文件还原 * 并选择 * 来宾配置 * 选项卡。
+
在子系统会话监控器表追加信息中，您可以单击 * 。 * 在右列中。

. 为通知电子邮件中列出的虚拟磁盘选择子系统文件还原会话。
+
所有分区都分配有一个驱动器号，包括系统预留的分区。如果 VMDK 具有多个分区，则可以通过在子文件浏览页面顶部的驱动器字段的下拉列表中选择特定驱动器。

. 单击 * 浏览文件 * 图标可查看虚拟磁盘上的文件和文件夹列表。
+
双击文件夹以浏览并选择单个文件时，提取文件列表时可能会出现时间延迟，因为提取操作是在运行时执行的。

+
为了便于浏览，您可以在搜索字符串中使用筛选器。这些筛选器区分大小写，为 Perl 表达式，不含空格。默认搜索字符串为 ` 。` * 。下表显示了一些 Perl 搜索表达式示例。

+
|===
| 此表达式为… | 搜索… 


| 。 | 除换行符以外的任何字符。 


| * | 任意字符串。这是默认值。 


| 答 | 字符 a. 


| AB | 字符串 AB 。 


| a [ 竖条 ] b | 字符 a 或 b 


| 答 * | 字符 a 的零个或多个实例 


| A+ | 字符的一个或多个实例 a 


| 答 | 字符 a 的零个或一个实例 


| a ｛ x ｝ | 字符 a 的实例数恰好为 x 个 


| a ｛ x ， ｝ | 字符 a 的实例数至少为 x 个 


| a ｛ x ， y ｝ | 字符 A 的实例数至少 x 个，最多 y 个。 


| \ | 转义特殊字符。 
|===
+
" 子系统文件浏览 " 页面除了显示所有其他文件和文件夹之外，还显示所有隐藏的文件和文件夹。

. 选择要还原的一个或多个文件或文件夹，然后单击 * 选择还原位置 * 。
+
要还原的文件和文件夹将在 " 选定文件 " 表中列出。

. 在 * 选择还原位置 * 页面中，指定以下内容：
+
|===
| 选项 | Description 


| 还原到路径 | 输入要还原选定文件的子系统的 UNC 共享路径。IPv4 示例： ` \\10.0.0.136.65\c$` IPv6 示例： ` \\fd20-8b1e-b255-832e--61.ipv6-literal.net\C\restore` 


| 原始文件是否存在  a| 
如果要还原的文件或文件夹已位于还原目标上，请选择要采取的操作：始终覆盖或始终跳过。


NOTE: 如果此文件夹已存在，则此文件夹的内容将与现有文件夹合并。



| 成功还原后断开来宾会话 | 如果希望在还原操作完成后删除子文件还原会话，请选择此选项。 
|===
. 单击 * 还原 * 。
+
您可以在信息板作业监控器中查看还原操作的进度，也可以等待电子邮件通知。发送电子邮件通知所需的时间取决于完成还原操作所需的时间长度。

+
此通知电子邮件包含一个附件，其中包含还原操作的输出。如果还原操作失败，请打开追加信息的附件。


