---
sidebar: sidebar 
permalink: scpivs44_migration_overview.html 
keywords:  
summary:  
---
= 迁移概述
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
migration 命令仅从 #SnapCenter 4.0 及更高版本 # 迁移元数据。如果您使用的是早期版本的 SnapCenter ，则必须先升级，然后才能进行迁移。

* 迁移的内容包括
+
** 迁移的内容
+
SnapCenter 元数据，包括存储系统，自定义限制以及 SnapCenter 配置文件，策略，资源组，备份元数据和挂载中的电子邮件设置。（迁移遇到预处理或后处理脚本时失败）

** 未迁移的内容
+
为资源组配置的预脚本和后脚本

+
活动子文件还原会话，子文件还原凭据和代理 VM

+
如果在子系统文件还原会话处于活动状态时开始迁移，则会删除此会话，并且不会卸载连接的磁盘。您可能需要手动删除连接的磁盘。

+
`sCBR.override` 配置文件



* SnapCenter 主机已暂停
+
为确保迁移成功，迁移命令会暂停已向 SnapCenter 注册的所有主机。迁移过程成功完成后， SnapCenter 主机将恢复。

* 迁移 cmdlet 过程
+
对于已向SnapCenter注册的适用于VMware vSphere的SnapCenter插件的每个实例、必须使用Windows PowerShell cmdlet `invoke-SCVOVAMigration` 。

+
cmdlet 可执行以下操作：

+
** 暂停所有计划，以防止迁移期间出现作业失败。成功迁移后，系统会自动重新启用计划。
** 迁移存储连接和元数据。
** 为迁移后备份创建备份计划。
** 从 Windows 主机卸载适用于 VMware vSphere 的现有 SnapCenter 插件。
+
如果适用于VMware vSphere的SnapCenter插件安装在SnapCenter服务器主机上、并且为SnapCenter存储库配置了保护、则迁移过程还会卸载基于Windows的插件软件包、其中包含适用于VMware vSphere的SnapCenter插件和适用于Windows的SnapCenter插件。 然后重新安装最新版本的适用于Windows的SnapCenter插件以支持存储库保护。SnapCenter 图形用户界面中的主机类型从 "vsphere" 更改为 "Windows" 。

** 从 Windows SnapCenter 服务器中删除 vSphere 主机和资源组。
** 激活适用于VMware vSphere的基于Linux的SnapCenter插件上的备份作业。
** 向SnapCenter注册适用于VMware vSphere的SnapCenter插件`的vSphere主机、以支持对虚拟化数据库和文件系统进行基于应用程序的备份(基于VMDK备份的应用程序)。


* 元数据的存储位置
+
用于基于应用程序的 VMDK 备份的元数据存储在 SnapCenter 服务器存储库中。VM和数据存储库备份的元数据存储在适用于VMware vSphere的SnapCenter插件MySQL存储库中。


