---
sidebar: sidebar 
permalink: scpivs44_restore_guest_files_and_folders_overview.html 
keywords:  
summary:  
---
= 工作流，前提条件和限制
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以从 Windows 子操作系统上的虚拟机磁盘（ VMDK ）还原文件或文件夹。



== 子系统还原工作流

子操作系统还原操作包括以下步骤：

. 附加
+
将虚拟磁盘连接到子虚拟机或代理虚拟机并启动子文件还原会话。

. 请稍候
+
等待连接操作完成，然后才能浏览和还原。连接时

+
操作完成，系统会自动创建子文件还原会话，并会发送电子邮件通知

+
已发送。

. 选择文件或文件夹
+
在子文件还原会话中浏览 VMDK ，然后选择一个或多个要还原的文件或文件夹。

. 还原
+
将选定文件或文件夹还原到指定位置。





== 还原子系统文件和文件夹的前提条件

在 Windows 子操作系统上从 VMDK 还原一个或多个文件或文件夹之前，您必须了解所有要求。

* 必须安装并运行 VMware Tools 。
+
SnapCenter 使用 VMware Tools 中的信息与 VMware 子操作系统建立连接。

* Windows 子操作系统必须运行 Windows Server 2008 R2 或更高版本。
+
有关受支持版本的最新信息，请参见 https://mysupport.netapp.com/matrix/imt.jsp?components=91324;&solution=1517&isHWU&src=IMT["NetApp 互操作性表工具（ IMT ）"^]。

* 目标 VM 的凭据必须指定内置域管理员帐户或内置本地管理员帐户。用户名必须为 "Administrator" 。 在开始还原操作之前，必须为要将虚拟磁盘连接到的虚拟机配置凭据。连接操作和后续还原操作都需要这些凭据。工作组用户可以使用内置的本地管理员帐户。
+

IMPORTANT: 如果您必须使用非内置管理员帐户，但在 VM 中具有管理权限的帐户，则必须在子 VM 上禁用 UAC 。

* 您必须知道要从中还原的备份 Snapshot 副本和 VMDK 。
+
适用于 VMware vSphere 的 SnapCenter 插件不支持搜索要还原的文件或文件夹。因此，在开始之前，您必须了解与 Snapshot 副本和相应 VMDK 相关的文件或文件夹的位置。

* 要连接的虚拟磁盘必须位于 SnapCenter 备份中。
+
包含要还原的文件或文件夹的虚拟磁盘必须位于使用适用于 VMware vSphere 的 SnapCenter 插件虚拟设备执行的 VM 备份中。

* 要使用代理 VM ，必须配置代理 VM 。
+
如果要将虚拟磁盘连接到代理 VM ，则必须先配置代理 VM ，然后才能开始连接和还原操作。

* 对于非英文字母名称的文件，您必须将其还原到目录中，而不是作为单个文件。
+
您可以通过还原文件所在的目录来还原非字母名称的文件，例如日语的 kanji 。

* 不支持从 Linux 子操作系统还原
+
您不能从运行 Linux 子操作系统的虚拟机还原文件和文件夹。但是，您可以连接 VMDK ，然后手动还原文件和文件夹。有关支持的子操作系统的最新信息，请参见 https://mysupport.netapp.com/matrix/imt.jsp?components=91324;&solution=1517&isHWU&src=IMT["NetApp 互操作性表工具（ IMT ）"^]。





== 子文件还原限制

在从子操作系统还原文件或文件夹之前，您应了解此功能不支持的内容。

* 您不能在子操作系统中还原动态磁盘类型。
* 如果还原加密文件或文件夹，则不会保留加密属性。您不能将文件或文件夹还原到加密的文件夹。
* " 子系统文件浏览 " 页面将显示隐藏的文件和文件夹，您无法对其进行筛选。
* 您无法从 Linux 子操作系统还原。
+
您不能从运行 Linux 子操作系统的虚拟机还原文件和文件夹。但是，您可以连接 VMDK ，然后手动还原文件和文件夹。有关支持的子操作系统的最新信息，请参见 https://mysupport.netapp.com/matrix/imt.jsp?components=91324;&solution=1517&isHWU&src=IMT["NetApp 互操作性表工具（ IMT ）"^]。

* 您不能从 NTFS 文件系统还原到 FAT 文件系统。
+
当您尝试从 NTFS 格式还原到 FAT 格式时，不会复制 NTFS 安全描述符，因为 FAT 文件系统不支持 Windows 安全属性。

* 您不能从克隆的 VMDK 或未初始化的 VMDK 还原子系统文件。
* 如果备份是在运行 ONTAP 9.2 或更高版本的系统上执行的，并且 VMware 一致性选项处于打开状态，则无法从二级备份进行还原。
* 您不能还原文件的目录结构。
+
如果选择还原嵌套目录中的文件，则不会使用相同的目录结构还原该文件。不会还原目录树，只会还原文件。如果要还原目录树，可以复制结构顶部的目录本身。


