---
sidebar: sidebar 
permalink: scpivs44_concepts_overview.html 
keywords:  
summary: 适用于 VMware vSphere 的 SnapCenter 插件是一种独立虚拟设备（开放式虚拟设备格式），可为 VM 和数据存储库提供数据保护服务，并支持为基于 SnapCenter 应用程序的插件提供数据保护服务。本文档介绍如何部署和使用适用于 VMware vSphere 的 SnapCenter 插件，并提供了快速入门信息。 
---
= 产品概述
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:firstname: [.lead]
:author: [.lead]
:authorinitials: [
:authors: [.lead]
:revnumber: 
:revdate: and supports data protection services for SnapCenter application-based plug-ins. This document describes how to deploy and use SnapCenter Plug-in for VMware vSphere and includes quick start information.


适用于 VMware vSphere 的 SnapCenter 插件部署为基于 Linux 的虚拟设备。

适用于VMware vSphere的SnapCenter插件为您的环境添加了以下功能：

* 支持 VM 一致和崩溃一致的数据保护操作。
+
您可以在vCenter中使用VMware vSphere客户端GUI执行VMware虚拟机(传统VM和VVol VM)、VMDK和数据存储库的所有备份和还原操作。对于 VVol 虚拟机（ VVol 数据存储库中的虚拟机），仅支持崩溃状态一致的备份。您还可以还原 VM 和 VMDK 以及还原子操作系统上的文件和文件夹。

+
备份 VM ， VMDK 和数据存储库时，此插件不支持 RDM 。VM 的备份作业会忽略 RDM 。如果需要备份 RDM ，则必须使用基于 SnapCenter 应用程序的插件。

+
适用于VMware vSphere的SnapCenter插件包括一个MySQL数据库、其中包含适用于VMware vSphere的SnapCenter插件元数据。为了实现虚拟机一致和崩溃状态一致的数据保护，您无需安装 SnapCenter 服务器。

* 支持应用程序一致的（基于 VMDB/RDM 的应用程序）数据保护操作。
+
您可以使用 SnapCenter 图形用户界面和相应的 SnapCenter 应用程序插件对 VM 上的主存储和二级存储上的数据库和文件系统执行所有备份和还原操作。

+
SnapCenter本机利用适用于VMware vSphere的SnapCenter插件对VMDK、原始设备映射(Raw Device Mappings、RDM)和NFS数据存储库执行所有数据保护操作。部署虚拟设备后，此插件将处理与 vCenter 的所有交互。适用于VMware vSphere的SnapCenter插件支持所有基于SnapCenter应用程序的插件。

+
SnapCenter不支持同时为数据库和VM创建一个快照。虚拟机和数据库的备份必须单独计划和运行、这样会创建单独的Snapshot、即使数据库和虚拟机托管在同一个卷中也是如此。使用SnapCenter 图形用户界面计划数据库应用程序备份；使用VMware vSphere客户端图形用户界面计划虚拟机和数据存储库备份。

* 要创建VM一致的Snapshot、需要使用VMware工具
+
如果未安装并运行VMware工具、则不会暂停文件系统、并创建崩溃状态一致的Snapshot。

* 在 SAN （ VMFS ）环境中执行还原操作需要使用 VMware Storage vMotion
+
VMware 文件系统（ VMFS ）的还原工作流利用了 VMware Storage vMotion 功能。Storage vMotion 是 vSphere 标准许可证的一部分，但 vSphere Essentials 或 Essentials Plus 许可证不提供。

+
NFS 环境中的大多数还原操作都使用原生 ONTAP 功能（例如单个文件 SnapRestore ），而不需要 VMware Storage vMotion 。

* 要配置VMware vVol VM、需要使用适用于VMware vSphere的ONTAP工具。
+
您可以使用ONTAP 工具在ONTAP 和VMware Web Client中为VVOL配置和配置存储。

+
有关详细信息、请参见 https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/index.html["适用于 VMware vSphere 的 ONTAP 工具"^]

* 适用于VMware vSphere的SnapCenter插件作为虚拟设备部署在Linux VM中
+
尽管虚拟设备必须作为Linux VM安装、但适用于VMware vSphere的SnapCenter插件同时支持基于Windows和基于Linux的vCenter。SnapCenter 本机使用此插件，无需用户干预，即可与 vCenter 进行通信，以支持基于 SnapCenter 应用程序的插件，这些插件可在 Windows 和 Linux 虚拟化应用程序上执行数据保护操作。



除了这些主要功能之外、适用于VMware vSphere的SnapCenter插件还支持iSCSI、光纤通道、FCoE、NFS 3.0/4.1、VMFS 5.0/6.0、 和基于TCP的NVMe。

有关受支持版本的最新信息、请参阅 https://imt.netapp.com/matrix/imt.jsp?components=121034;&solution=1517&isHWU&src=IMT["NetApp 互操作性表工具"^] (IMT)。

有关NFS协议和ESXi主机的信息、请参阅VMware提供的vSphere存储文档。

有关SnapCenter数据保护的信息，请参阅中SnapCenter插件的数据保护信息 http://docs.netapp.com/us-en/snapcenter/index.html["SnapCenter 文档"^]。

有关支持的升级和迁移路径的信息，请参见 link:scpivs44_release_notes.html["适用于 VMware vSphere 的 SnapCenter 插件发行说明"^]。
