---
sidebar: sidebar 
permalink: scpivs44_minimum_vcenter_privileges_required.html 
keywords:  
summary: 在开始部署适用于 VMware vSphere 的 SnapCenter 插件之前，您应确保具有所需的最低 vCenter 特权。 
---
= 所需的最低 vCenter 权限
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在开始部署适用于 VMware vSphere 的 SnapCenter 插件之前，您应确保具有所需的最低 vCenter 特权。



== vCenter 管理员角色所需的特权

数据存储库.AllocateSpace数据存储库。浏览数据存储库.Delete数据存储库.FileManagement数据存储库.Move数据存储库.重 命名扩展.Register扩展.Unregistrate扩展.Update Host.Config.AdvancedConfig Host.Config.Settings Host.Config.Storage Host.Local.CreateVM Host.Local.DeleteVM Host.Local.RecomedVirtual Machine Network.VirtualMachine.VirtualDisk.Unigrate.Unigrate.Unigrate.VirtualMachine.Unigrate.VirtualMachine.Unigrate.VirtualMachine.Unigrate.VirtualMachine.Unigrate.VirtualMachine.Unigrate.VirtualMachine.Unigrate.VirtualMachine.Unigrate.VirtualMachine.Unigrate.VirtualMachine.Unigrate.VirtualMachine.Resety.VirtualMachine.Unigrate.VirtualMachine.Res.Res.Resete.Disk.Res.Res.VirtualMachine.Disk.Unigrate.VirtualMachine.Unigrate.VirtualMachine.Unigrate.VirtualMachine.Unigrate.VirtualMachine.Disk.Res.VirtualMachine.Unigrate.VirtualMachine.Unigrate.VirtualMachine.Un



== 适用于 VMware vCenter 的 SnapCenter 插件所需的特权

|===


| * 权限 * | *标签* 


| netappSCC.Guest.RestoreFile | 子系统文件还原 


| netappSCC.Recovery.MountUnMount | 挂载/卸载 


| netappSCC.Backup.DeleteBackupJob | 删除资源组/备份 


| netappSCC.Configure.ConfigureStorageSystems.Delete | 删除存储系统 


| netappSCV视图 | 查看 


| netappSCC.Recover.RecoverVM | 恢复VM 


| netappSCC.Configure.ConfigureStorageSystems.AddUpdate | 添加/修改存储系统 


| netappSCC.Backup.BackupNow | 立即备份 


| netappSCC.Guest.Configure | 子系统配置 


| netappSCC.Configure.ConfigureSnapCenterServer | 配置SnapCenter 服务器 


| netappSCC.Backup.BackupScheduleed | 创建资源组 
|===