---
sidebar: sidebar 
permalink: scpivs44_information_not_displayed_after_upgrading_to_a_new_patch_of_the_same_release.html 
keywords:  
summary: 将适用于 VMware vSphere 的 SnapCenter 插件升级到同一版本的新修补程序后，信息板和作业监控器中可能不会显示最近的作业或其他信息。 
---
= 升级到同一版本的新修补程序后，不会显示信息
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
将适用于 VMware vSphere 的 SnapCenter 插件升级到同一版本的新修补程序后，信息板和作业监控器中可能不会显示最近的作业或其他信息。

如果要升级到同一版本的新修补程序，则必须清除 vCenter Web Server 上适用于 VMware vSphere 的 SnapCenter 插件缓存，并在升级或注册之前重新启动服务器。

如果未清除插件缓存，则在以下情况下，信息板和作业监控器不会显示最近的作业：

* 适用于 VMware vSphere 的 SnapCenter 插件是使用 vCenter 部署的，之后升级到同一版本中的修补程序。
* SnapCenter VMware 虚拟设备部署在 vCenter 1 中。之后、此适用于VMware vSphere的SnapCenter插件注册到了新的vCenter2。此时将使用修补程序创建一个适用于VMware vSphere的SnapCenter插件的新实例、并将其注册到vCenter1。但是、由于vCenter1仍具有适用于VMware vSphere的第一个SnapCenter插件中缓存的插件、而没有修补程序、因此需要清除缓存。


根据服务器操作系统的类型，缓存位于以下位置：

* vCenter Server Linux 设备
+
` /etc/vmware/vsphere-client/vc-packages/vsphere-client-serenation/`

* Windows 操作系统
+
`%PROGRAMFILES%/VMware/vSphere client/vc-packages/vsphere-client-serenity/`





== 临时解决策（如果在清除缓存之前已升级）

. 登录到适用于 VMware vSphere 的 SnapCenter 插件管理 GUI 。
+
部署适用于VMware vSphere的SnapCenter插件时、将显示IP地址。

. 在左侧导航窗格中选择*配置*，然后在*插件详细信息*部分中选择服务选项以禁用此插件。
+
已禁用适用于VMware vSphere的SnapCenter插件服务、并且此扩展已在vCenter中取消注册。

. 找到 `vsphere-client-serenity` 文件夹中、然后找到 `com.netapp.scv.client-<release-number>` 文件夹并将其删除。
+
每个版本的文件夹名称都会发生变化。

. 重新启动 vCenter Server 。
. 登录到VMware vSphere客户端。
. 在左侧导航窗格中选择*配置*，然后在*插件详细信息*部分中选择服务选项以启用该插件。
+
已启用适用于VMware vSphere的SnapCenter插件服务、并且已在vCenter中注册此扩展。


