---
sidebar: sidebar 
permalink: scpivs44_restore_vmdks_from_backups.html 
keywords:  
summary: 您可以从传统VM或VVol VM的主备份或二级备份还原现有VMDK、或者从已删除或断开的VMDK。 
---
= 从备份还原 VMDK
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以从传统VM或VVol VM的主备份或二级备份还原现有VMDK、或者从已删除或断开的VMDK。

您可以将虚拟机上的一个或多个虚拟机磁盘（ VMDK ）还原到同一数据存储库。


TIP: 要提高 NFS 环境中还原操作的性能，请启用 VMware 应用程序 vStorage API for Array Integration （ VAAI ）。

.开始之前
* 必须存在备份。
+
您必须已使用适用于 VMware vSphere 的 SnapCenter 插件创建虚拟机的备份。

* 虚拟机不得处于传输状态。
+
要还原的虚拟机不能处于 vMotion 或 Storage vMotion 状态。



.关于此任务
* 如果 VMDK 已从 VM 中删除或断开，则还原操作会将 VMDK 连接到 VM 。
* 如果虚拟机所在的 FabricPool 存储层不可用，还原操作可能会失败。
* 连接和还原操作使用默认 SCSI 控制器连接 VMDK 。但是、如果备份了连接到具有NVMe磁盘的VM的VMDK、则连接和还原操作将使用NVMe控制器(如果可用)。


.步骤
. 在VMware vSphere客户端图形用户界面中、单击工具栏中的*菜单*、然后从下拉列表中选择*虚拟机和模板*。
. 在左侧导航器窗格中、右键单击某个虚拟机、然后在下拉列表中选择*适用于VMware vSphere的SnapCenter插件*、并在二级下拉列表中选择*还原*。
. 在 * 还原 * 向导的选择备份页面上，选择要从中还原的备份副本。
+
您可以搜索特定备份名称或部分备份名称、也可以通过单击筛选器图标并选择日期和时间范围来筛选备份列表、选择是否需要包含VMware快照的备份、是否需要挂载备份以及主位置或二级位置。单击 * 确定 * 以返回到向导。

. 在 * 选择范围 * 页面上，选择还原目标。
+
|===
| 还原到… | 指定还原目标… 


| 原始数据存储库 | 从下拉列表中选择 * 特定磁盘 * ，然后单击 * 下一步 * 。在数据存储库选择表中，您可以选择或取消选择任何 VMDK 。 


| 备用位置中的备用数据存储库 | 单击目标数据存储库，然后从列表中选择其他数据存储库。 
|===
. 在*Select Location*页面上，选择要还原的快照(主快照或二级快照)。
. 查看摘要页面，然后单击 * 完成 * 。
. 可选：单击屏幕底部的 * 近期任务 * ，监控操作进度。
. 刷新屏幕以显示更新后的信息。

