---
sidebar: sidebar 
permalink: scpivs44_add_a_single_vm_or_datastore_to_a_resource_group.html 
keywords:  
summary: 您可以将单个虚拟机或数据存储库快速添加到适用于 VMware vSphere 的 SnapCenter 插件管理的任何现有资源组中。 
---
= 将单个虚拟机或数据存储库添加到资源组
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以将单个虚拟机或数据存储库快速添加到适用于 VMware vSphere 的 SnapCenter 插件管理的任何现有资源组中。

.关于此任务
您可以添加 SAN 和 NAS 数据存储库，但不能添加 VSAN 或 VVol 数据存储库。

.步骤
. 在 VMware vSphere Web Client 图形用户界面中，单击工具栏中的 * 菜单 * ，然后导航到要添加的虚拟机或数据存储库。
. 在左侧导航器窗格中，右键单击虚拟机或数据存储库，从下拉列表中选择 * NetApp SnapCenter * ，然后从二级下拉列表中选择 * 添加到资源组 * 。
+
系统会首先检查 SnapCenter 是否管理选定虚拟机所在的存储系统并与该存储系统兼容，然后显示 * 添加到资源组 * 页面。如果显示消息 SnapCenter 兼容性错误` ，则选定虚拟机与 SnapCenter 不兼容，您必须先将相应的 Storage VM 添加到 SnapCenter 。

. 在 * 添加到资源组 * 页面中，选择一个资源组，然后单击 * 确定 * 。
+
单击 * 确定 * 时，系统会首先检查 SnapCenter 是否管理选定虚拟机或数据存储库所在的存储并与其兼容。

+
如果显示消息 `Sselected <resource-name> is not SnapCenter compatible` ，则选定虚拟机或数据存储库与 SnapCenter 不兼容。请参见 link:scpivs44_create_resource_groups_for_vms_and_datastores.html#manage-compatibility-check-failures["管理兼容性检查失败"] 有关详细信息 ...


