---
sidebar: sidebar 
permalink: scpivs44_manage_storage_systems.html 
keywords:  
summary: 在使用VMware vSphere客户端备份或还原VM或数据存储库之前、必须添加存储。 
---
= 管理存储系统
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在使用VMware vSphere客户端备份或还原VM或数据存储库之前、必须添加存储。



== 修改 Storage VM

您可以使用VMware vSphere客户端修改已在适用于VMware vSphere的SnapCenter 插件中注册并用于VM数据保护操作的集群和Storage VM的配置。

如果修改作为集群一部分自动添加的 Storage VM （有时称为隐式 Storage VM ），则该 Storage VM 将更改为显式 Storage VM ，并且可以单独删除，而不更改该集群中其余的 Storage VM 。如果身份验证方法是通过证书进行的、则在存储系统页面上、用户名显示为不适用；只有集群列表中的显式Storage VM才会显示用户名、并将ExploricitSVM标志设置为true。所有 Storage VM 始终列在关联集群下。


IMPORTANT: 如果您使用SnapCenter用户界面为基于应用程序的数据保护操作添加了存储虚拟机，则必须使用相同的用户界面来修改这些存储虚拟机。

.步骤
. 在选择控制阀插件的左侧导航窗格中，选择*存储系统*。
. 在*Storage Systems*页面上，选择要修改的Storage VM，然后选择*Edit*。
. 在*编辑存储系统*窗口中，输入新值，然后选择*更新*以应用更改。




== 删除 Storage VM

您可以使用VMware vSphere客户端从vCenter中的清单中删除Storage VM。


NOTE: 如果您使用SnapCenter用户界面为基于应用程序的数据保护操作添加了存储虚拟机，则必须使用相同的用户界面来修改这些存储虚拟机。

.开始之前
您必须先卸载 Storage VM 中的所有数据存储库，然后才能删除此 Storage VM 。

.关于此任务
如果某个资源组的备份驻留在要删除的 Storage VM 上，则该资源组的后续备份将失败。

.步骤
. 在选择控制阀插件的左侧导航窗格中，选择*存储系统*。
. 在*Storage Systems*页面上，选择要删除的Storage VM，然后选择*Delete*。
. 在“*删除存储系统*”确认框中，选中“*删除存储系统*”复选框，然后选择“是”进行确认。*注意：*仅支持ESXi主机7.0U1及更高版本。
+
link:scpivs44_restart_the_vmware_vsphere_web_client_service.html["重新启动VMware vSphere客户端服务"](英文)


