---
sidebar: sidebar 
permalink: scpivs44_restore_vms_from_backups.html 
keywords:  
summary: 还原虚拟机时，您可以使用所选的备份副本覆盖现有内容，也可以创建虚拟机的副本。 
---
= 从备份还原 VM
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
还原虚拟机时，您可以使用所选的备份副本覆盖现有内容，也可以创建虚拟机的副本。

您可以将 VM 还原到以下位置：

* 还原到原始位置
+
** 挂载到原始 ESXi 主机上的原始数据存储库（此操作会覆盖原始虚拟机）


* 还原到备用位置
+
** 挂载到原始 ESXi 主机上的其他数据存储库
** 挂载到由同一 vCenter 管理的其他 ESXi 主机上的原始数据存储库
** 挂载到由同一 vCenter 管理的不同 ESXi 主机上的其他数据存储库
** 挂载在其他 ESXi 主机上的另一个数据存储库，该主机由其他 vCenter 以链接模式管理





NOTE: 还原到其他位置时，适用于 VMware vSphere 的 SnapCenter 插件必须在作为还原操作目标的链接 vCenter 中运行。目标数据存储库必须具有足够的空间。


NOTE: 不支持以下还原工作流：添加一个 Storage VM ，然后对该 VM 执行备份，然后删除该 Storage VM 并添加一个包含同一 Storage VM 的集群，最后尝试还原原始备份。


TIP: 要提高 NFS 环境中还原操作的性能，请启用 VMware 应用程序 vStorage API for Array Integration （ VAAI ）。

.开始之前
* 必须存在备份。
+
您必须先使用 SnapCenter VMware 插件创建虚拟机备份，然后才能还原虚拟机。

+

NOTE: 如果虚拟机的 Snapshot 副本是由适用于 VMware vSphere 的 SnapCenter 插件以外的软件执行的，则还原操作无法成功完成。

* 虚拟机不得处于传输状态。
+
要还原的虚拟机不能处于 vMotion 或 Storage vMotion 状态。

* HA 配置错误
+
在将备份还原到其他位置之前，请确保 vCenter ESXi 主机摘要屏幕上未显示 HA 配置错误。

* 还原到其他位置
+
还原到其他位置时，适用于 VMware vSphere 的 SnapCenter 插件必须在作为还原操作目标的 vCenter 中运行。目标数据存储库必须具有足够的空间。



.关于此任务
* 虚拟机已取消注册并重新注册
+
VM 的还原操作将取消注册原始 VM ，从备份 Snapshot 副本还原 VM ，并在同一 ESXi 服务器上注册名称和配置相同的已还原 VM 。还原后，您必须手动将 VM 添加到资源组。

* 还原数据存储库
+
您不能还原数据存储库，但可以还原数据存储库中的任何 VM 。

* 虚拟机的 VMware 一致性 Snapshot 失败
+
即使虚拟机的 VMware 一致性快照失败，也会对虚拟机进行备份。您可以在还原向导中查看备份副本中包含的实体，并将其用于还原操作。

* 如果虚拟机所在的 FabricPool 存储层不可用，还原操作可能会失败。


.步骤
. 在 VMware vSphere Web Client 图形用户界面中，单击工具栏中的 * 菜单 * ，然后从下拉列表中选择 * 虚拟机和模板 * 。
+

NOTE: 如果要还原已删除的虚拟机，则添加到 SnapCenter VMware 插件的 Storage VM 凭据必须为 `vsadmin` 或与 `vsadmin` 具有所有相同权限的用户帐户。主机必须位于运行 ONTAP 8.2.2 或更高版本的存储系统上。

. 在左侧导航器窗格中，右键单击某个虚拟机，然后从下拉列表中选择 * NetApp SnapCenter * ，然后在二级下拉列表中选择 * 还原 * 以启动向导。
. 在 * 还原 * 向导的 * 选择备份 * 页面上，选择要还原的备份 Snapshot 副本。
+
您可以搜索特定备份名称或部分备份名称，也可以通过单击筛选器图标并选择日期和时间范围，选择是否要包含 VMware Snapshot 的备份，是否要挂载备份以及位置来筛选备份列表。单击 * 确定 * 以返回到向导。

. 在 * 选择范围 * 页面上，在 * 还原范围 * 字段中选择 * 整个虚拟机 * ，然后选择还原位置，然后输入应将备份挂载到的目标信息。
+
在 * 虚拟机名称 * 字段中，如果存在相同的虚拟机名称，则新的虚拟机名称格式为 ` <vm_name>_<timestamp>` 。

+
还原部分备份时，还原操作会跳过 * 选择范围 * 页面。

. 在 * 选择位置 * 页面上，选择已还原数据存储库的位置。
+
在适用于 VMware vSphere 4.5 及更高版本的 SnapCenter 插件中，您可以为 FlexGroup 卷选择二级存储。

. 查看摘要页面，然后单击 * 完成 * 。
. 可选：单击屏幕底部的 * 近期任务 * ，监控操作进度。
+
刷新屏幕以显示更新后的信息。



.完成后
* 更改 IP 地址
+
如果还原到其他位置，则必须更改新创建的虚拟机的 IP 地址，以避免在配置静态 IP 地址时发生 IP 地址冲突。

* 将已还原的 VM 添加到资源组
+
尽管虚拟机已还原，但它们不会自动添加到以前的资源组中。因此，您必须手动将还原的 VM 添加到相应的资源组。


