---
sidebar: sidebar 
permalink: scpivs44_view_status_information.html 
keywords:  
summary: 您可以在vSphere客户端信息板上查看状态信息。状态信息每小时更新一次。 
---
= 查看状态信息
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以在vSphere客户端信息板上查看状态信息。状态信息每小时更新一次。

.步骤
. 在vSphere客户端的左侧导航器窗格中、单击*信息板*、选择一个vCenter Server、然后单击信息板窗格中的*状态*选项卡。
. 查看概述状态信息或单击链接以查看更多详细信息，如下表所示。
+
|===
| 此信息板图块… | 显示以下信息… 


 a| 
最近的作业活动
 a| 
最近三到五个备份，还原和挂载作业。

** 单击作业 ID 可查看有关该作业的更多详细信息。
** 单击 * 查看全部 * 转到作业监控选项卡，了解有关所有作业的更多详细信息。




 a| 
作业
 a| 
在选定时间窗口内执行的每个作业类型（备份，还原和挂载）的计数。将光标悬停在图表的某个部分上可查看该类别的更多详细信息。



 a| 
最新保护摘要
 a| 
选定时间窗口内主虚拟机和二级虚拟机或数据存储库的数据保护状态摘要。

** 单击下拉菜单以选择 * 虚拟机 * 或 * 数据存储库 * 。
** 对于二级存储，请选择 * SnapVault * 或 * SnapMirror * 。
** 将光标悬停在图表的某个部分上，可查看该类别中的 VM 或数据存储库数量。在成功类别中，列出了每个资源的最新备份。
** 您可以通过编辑配置文件来更改时间窗口。默认值为 7 天。有关详细信息，请参见 link:scpivs44_customize_your_configuration.html["自定义配置"]。
** 每个主备份或二级备份之后都会更新内部计数器。信息板磁贴每六小时刷新一次。无法更改刷新时间。注意：如果使用镜像 - 存储保护策略，则保护摘要的计数器将显示在 SnapVault 摘要图表中，而不是 SnapMirror 图表中。




 a| 
Configuration
 a| 
适用于 VMware vSphere 的 SnapCenter 插件所管理的每种类型的对象的总数。



 a| 
存储
 a| 
生成的Snapshot、SnapVault和SnapMirror Snapshot总数以及用于主快照和二级快照的存储量。折线图会分别绘制连续 90 天内每天的主存储和二级存储消耗情况。存储信息每24小时在凌晨1：08更新一次
存储节省量是逻辑容量(Snapshot节省量加上已用存储)与主存储物理容量之比。条形图显示了存储节省量。

将光标悬停在图表上的一行上可查看详细的每日结果。

|===

