---
sidebar: sidebar 
permalink: scpivs44_ontap_rbac_features_in_snapcenter.html 
keywords:  
summary: '适用于VMware vSphere的SnapCenter插件可与vCenter Server RBAC、SnapCenter RBAC (在需要支持基于应用程序的操作时)和ONTAP RBAC结合使用、以确定特定用户可以对特定存储系统上的对象执行哪些SnapCenter任务。' 
---
= 适用于 VMware vSphere 的 SnapCenter 插件中的 ONTAP RBAC 功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/



NOTE: ONTAP RBAC 仅适用于 SnapCenter 服务器应用程序一致（基于 VMDK 的应用程序）作业。

[role="lead"]
通过 ONTAP 基于角色的访问控制（ Role-Based Access Control ， RBAC ），您可以控制对特定存储系统的访问以及用户可以对这些存储系统执行的操作。适用于VMware vSphere的SnapCenter插件可与vCenter Server RBAC、SnapCenter RBAC (在需要支持基于应用程序的操作时)和ONTAP RBAC结合使用、以确定特定用户可以对特定存储系统上的对象执行哪些SnapCenter任务。

SnapCenter 使用您设置的凭据（用户名和密码）对每个存储系统进行身份验证，并确定可以对该存储系统执行哪些操作。适用于VMware vSphere的SnapCenter插件会为每个存储系统使用一组凭据。这些凭据决定了可对该存储系统执行的所有任务；换言之，这些凭据适用于 SnapCenter ，而不是单个 SnapCenter 用户。

ONTAP RBAC 仅适用于访问存储系统以及执行与存储相关的 SnapCenter 任务，例如备份 VM 。如果您对特定存储系统没有适当的 ONTAP RBAC 特权，则无法对该存储系统上托管的 vSphere 对象执行任何任务。

每个存储系统都有一组关联的 ONTAP 特权。

同时使用 ONTAP RBAC 和 vCenter Server RBAC 具有以下优势：

* 安全性
+
管理员可以控制哪些用户可以在细化的 vCenter Server 对象级别和存储系统级别上执行哪些任务。

* 审核信息
+
在许多情况下， SnapCenter 会在存储系统上提供审核跟踪功能，您可以通过此功能将事件追溯到执行存储修改的 vCenter 用户。

* 可用性
+
您可以在一个位置维护控制器凭据。


